# # 1단계: build
# FROM node:20-alpine AS build
# WORKDIR /app
# COPY package.json package-lock.json ./
# RUN npm install
# COPY . .
# RUN npm run build

# # 2단계: nginx
# FROM nginx:alpine
# COPY --from=build /app/dist /usr/share/nginx/html